create table usuario(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
nome varchar(25) not null,
nome_social varchar(45) not null,
cpf varchar(14) not null,
email varchar(45) not null,
telefone varchar(14) not null,
pontos_troca integer,
conta_ativa boolean,
senha varchar(45) not null
);

create table endereco(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
cep varchar(9) not null,
cidade varchar(50) not null,
bairro varchar(50) not null,
rua varchar (50) not null,
numero varchar(4),
id_usuario integer,
foreign key(id_usuario) references usuario(id)
);

create table genero(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
nome varchar(50) not null
);

create table livro(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
titulo varchar(50) not null,
autor varchar(50) not null,
sinopse varchar(1000) not null,
detalhes varchar(1000) not null,
foto_livro varchar(150) not null,
disponibilidade boolean not null,
id_genero integer,
id_usuario integer,
foreign key(id_genero) references genero(id),
foreign key(id_usuario) references usuario(id)
);

create table notificacao(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
id_livro_desejado integer,
id_usuario_solicitante integer,
status varchar(50) not null,
foreign key(id_livro_desejado) references livro(id),
foreign key(id_usuario_solicitante) references usuario(id)
);

create table livro_usuario(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
id_livro integer,
id_notificacao integer,
foreign key(id_livro) references livro(id),
foreign key(id_notificacao) references notificacao(id)
);

create table troca(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
data date,
localidade varchar(50),
status varchar(50)
);

create table livro_troca(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
id_livro integer,
id_troca integer,
foreign key(id_livro) references livro(id),
foreign key(id_troca) references troca(id)
);

create table historico(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
id_livro integer,
id_usuario integer,
id_troca integer,
foreign key(id_livro) references livro(id),
foreign key(id_usuario) references usuario(id),
foreign key(id_troca) references troca(id)
);